# -*- coding: utf-8 -*-
"""CoreLearningAlgo-LinearRegression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pQcGDSbOuqf5gbh9Bn519p67qX6QTcXt
"""

# !pip install -q sklearn

# Commented out IPython magic to ensure Python compatibility.
# %tensorflow_version 2.x

from __future__ import absolute_import, division, print_function, unicode_literals

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import clear_output
from six.moves import urllib

# import tensorflow.compat.v2.feature_column as fc

from tensorflow import feature_column as fc
# feature = feature_column.numeric_column

import tensorflow as tf

"""data set - the titanic data set - likelyhood someone will survive on the Titanic"""

# Load dataset.

dftrain = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/train.csv')  # train
dfeval = pd.read_csv('https://storage.googleapis.com/tf-datasets/titanic/eval.csv')  # test
# print(dftrain.head())
y_train = dftrain.pop('survived')
# print(y_train)
y_eval = dfeval.pop('survived')
# print(dftrain.head())
print(dftrain.loc[0], y_train.loc[0])
# print(dftrain["age"])

dftrain.head()

dftrain.describe()

dftrain.shape

y_train.head()

dftrain.age.hist(bins=20)

dftrain.sex.value_counts().plot(kind='barh')

dftrain['class'].value_counts().plot(kind='barh')

pd.concat([dftrain, y_train], axis=1).groupby('sex').survived.mean().plot(kind='barh').set_xlabel('% survive')